apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
  namespace: data-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: hadoop
        image: hadoop/hadoop:3.3.4
        ports:
        - containerPort: 8020
        - containerPort: 9870
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop
  namespace: data-platform
spec:
  selector:
    app: hadoop
  ports:
    - port: 8020
      targetPort: 8020
    - port: 9870
      targetPort: 9870