apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-app.mongodb.fullname" . | default "mongodb-service" }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
  selector:
    app: {{ .Release.Name }}-mongodb
